from datetime import datetime

from models.Todo import Todo, Priority, Category
from models.TodoList import TodoList

from services.collector_service import Collector

class TodoService:
    def __init__(self):
        self.collector = Collector()

    # ---------------------------------------------------------------------------- #
    # ---------------------------------- Helpers --------------------------------- #
    # ---------------------------------------------------------------------------- #
    def _save_todos(self, todo_list: TodoList) -> None:
        """
        Saves Todo object collection

        :param todo_list: List of currently stored Todo objects
        """
        todo_list.repo.save_todos()

    def _save_if_result(self, result: bool, todo_list: TodoList) -> None:
        """ 
        Saves Todo object collection if change has been made 
        
        :param result: True if changes have been made else False
        :param todo_list: List of currently stored Todo objects
        """
        if result == True:
            self._save_todos(todo_list=todo_list)


    # ---------------------------------------------------------------------------- #
    # ---------------------------------- Methods --------------------------------- #
    # ---------------------------------------------------------------------------- #
    def create_todo(self, todo_list: TodoList) -> None:
        """
        Collects user input and creates a Todo object with the collected values

        :param todo_list: List of currently stored Todo objects
        """

        # ID autogenerated using length of current todo collection
        id = len(todo_list.get_all()) + 1

        title = self.collector.collect_non_blank("Todo Title: ").title()
        description = self.collector.collect_non_blank("Description: ")

        # Category must be one of work, personal, projects, learning, errands, health, finance, home, social, other
        # Priority must be one of low, medium, high, or critical
        category = self.collector.collect_enum_value(prompt="Category: ", classname=Category)
        priority = self.collector.collect_enum_value(prompt="Priority: ", classname=Priority)

        # Due date value may be blank
        due_date = self.collector.collect_due_date()

        todo = Todo(id=id, title=title, description=description, priority=priority, category=category, due_date=due_date)
        todo_list.add(todo)
        self._save_todos(todo_list=todo_list)

    def complete_todo(self, todo_list: TodoList) -> bool:
        """
        Collect input for ID of Todo object to complete and complete

        :param todo_list: List of currently stored Todo objects

        :return True: Operation was succesful
        :return False: Operation was unsuccessful
        """
        self.view_todos(todo_list=todo_list)

        todo = todo_list.get_todo_by_id(todo_id=self.collector.collect_todo_id())
        if todo is None:
            return False

        result = todo.complete()
        self._save_if_result(result=result, todo_list=todo_list)
        return result

    def uncomplete_todo(self, todo_list: TodoList) -> bool:
        """
        Collect input for ID of Todo object to uncomplete

        :param todo_list: List of currently stored Todo objects

        :return True: Operation Successful
        :return False: Operation Unsuccessful
        """
        self.view_todos(todo_list=todo_list)

        todo = todo_list.get_todo_by_id(todo_id=self.collector.collect_todo_id())
        if todo is None:
            return False

        result = todo.uncomplete()
        self._save_if_result(result=result, todo_list=todo_list)
        return result

    def delete_todo(self, todo_list: TodoList) -> bool:
        """
        Collect input for ID of Todo object to delete and remove from todo_list

        :param todo_list: List of currently stored Todo objects

        :return True: Operation successful
        :return False: Operation unsuccessful
        """
        self.view_todos(todo_list=todo_list)

        result = todo_list.remove(todo_id=self.collector.collect_todo_id())
        self._save_if_result(result=result, todo_list=todo_list)

        return result

    def view_todos(self, todo_list: TodoList) -> None:
        """
        Print out a list of the current Todo objects contained within the active repository

        :param todo_list: List of current stored Todo objects
        """
        print("\n=== Todos ===")
        for todo in todo_list.get_all():
            print(todo)