from datetime import datetime

from models.Todo import Todo, Priority, Category
from models.TodoList import TodoList

class TodoService:
    def create_todo(self, todo_list: TodoList):
        """
        Collects user input and creates a Todo object with the collected values

        :param todo_list: List of currently stored Todo objects
        """
        # ID autogenerated using length of current todo collection
        id = len(todo_list.get_all()) + 1

        title = input("Todo Title: ").strip().title()
        description = input("Description: ").strip()

        # Category must be one of work, personal, projects, learning, errands, health, finance, home, social, other
        while True:
            try:
                category = Category(input("Category: ").strip().lower())
                break
            except ValueError:
                print("Invalid Category.\n")

        # Priority must be one of low, medium, high, or critical
        while True:
            try:
                priority = Priority(input("Priority: ").strip().lower())
                break
            except ValueError:
                print("Invalid Priority.\n")

        # Due date value may be blank
        due_date = input("Due Date (Optional): ").strip()

        # Modify Due Date
        if due_date:
            due_date = datetime.strptime(due_date, "%Y-%m-%d")
        else:
            due_date = None

        todo = Todo(id=id, title=title, description=description, priority=priority, due_date=due_date)
        todo_list.add(todo)
        todo_list.repo.save_todos()

    def complete_todo(self, todo_list: TodoList) -> bool:
        """
        Collect input for ID of Todo object to complete and complete

        :param todo_list: List of currently stored Todo objects

        :return True: Operation was succesful
        :return False: Operation was unsuccessful
        """
        self.view_todos(todo_list=todo_list)

        todo_id = int(input("\nEnter todo ID: "))
        todo = todo_list.get_todo_by_id(todo_id=todo_id)
        if todo is None:
            return False

        result = todo.complete()
        if result:
            todo_list.repo.save_todos()
        return result

    def uncomplete_todo(self, todo_list: TodoList) -> bool:
        """
        Collect input for ID of Todo object to uncomplete

        :param todo_list: List of currently stored Todo objects

        :return True: Operation Successful
        :return False: Operation Unsuccessful
        """
        self.view_todos(todo_list=todo_list)

        todo_id = int(input("\nEnter todo ID: "))
        todo = todo_list.get_todo_by_id(todo_id=todo_id)
        if todo is None:
            return False

        result = todo.uncomplete()
        if result:
            todo_list.repo.save_todos()
        return result

    def delete_todo(self, todo_list: TodoList) -> bool:
        """
        Collect input for ID of Todo object to delete and remove from todo_list

        :param todo_list: List of currently stored Todo objects

        :return True: Operation successful
        :return False: Operation unsuccessful
        """
        self.view_todos(todo_list=todo_list)

        todo_id = int(input("\nEnter todo ID: "))
        result = todo_list.remove(todo_id=todo_id)
        if result:
            todo_list.repo.save_todos()
        return result

    def view_todos(self, todo_list: TodoList) -> None:
        """
        Print out a list of the current Todo objects contained within the active repository

        :param todo_list: List of current stored Todo objects
        """
        print("\n=== Todos ===")
        for todo in todo_list.get_all():
            print(todo)